import '@/styles/globals.css'
import axios from 'axios';
// import CRYPTOS from 'src/app/cryptos/depos'
import Nav from "@/components/Nav";
import footer from "@/components/Footer";
import { Space } from 'antd';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }){ 
  return (
    <html lang="en">
      <body>
        <div className='main'>
          <div className='gradient' />
        </div>

        <main className='app'>
          <Nav />
          {children}
          <footer/>
        </main>
      </body>
    </html>
  )
}
